# Generated by Django 4.1.5 on 2023-01-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='semester',
        ),
    ]
