# Generated by Django 4.1.5 on 2023-01-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_rename_id_user__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_id',
            new_name='id',
        ),
    ]
