# Generated by Django 4.1.5 on 2023-01-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Non-Tech', 'Non-Tech')], max_length=200, null=True),
        ),
    ]
