# Generated by Django 4.1.5 on 2023-01-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_alter_feed_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
