# Generated by Django 4.1.5 on 2023-01-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_feed_feed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Virtual', 'Virtual'), ('Hybrid', 'Hybrid'), ('In-Person', 'In-Person')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='post_date',
            field=models.DateField(auto_now=True),
        ),
    ]
